package gomark

import (
	"os"
	"path/filepath"
	"strings"
)

type App struct {
	Title string
	// Lang sets the <html lang> attribute (default "en").
	Lang string
	// ThemeColor sets the <meta name="theme-color"> value. When empty the
	// built-in light/dark defaults (#ffffff / #000000) are used.
	ThemeColor string
	// Description is the default meta/Open Graph description used for pages
	// that do not set one via frontmatter.
	Description string
	// LogoLight and LogoDark are the brand logo URLs for the light and dark
	// themes. When both are set the page swaps between them with the theme;
	// when neither is set the bundled logo is used.
	LogoLight string
	LogoDark  string
	// SEO image metadata.
	OGImagePath      string
	TwitterImagePath string
	TwitterSite      string // @handle for twitter:site
	TwitterCreator   string // @handle for twitter:creator
	ImageAlt         string // og:image:alt (defaults to the site title)
	// Footer is optional free text shown in the site footer.
	Footer string
	// NavLinks are top-of-page navigation links; SocialLinks render in the
	// footer. Both are fully configurable and replace nothing derived from the
	// content tree.
	NavLinks    []ConfigLink
	SocialLinks []ConfigLink
	// Analytics configures an optional analytics snippet injected on every page.
	Analytics    AnalyticsConfig
	ContentDir   string
	SidebarDepth int
	SiteURL      string
	ExportDir    string
	Mode         RenderMode
	// DisableRunner turns off the in-browser Go runner. Execution is
	// client-side (a WebAssembly build of the yaegi interpreter), so the
	// runner is on by default and needs no external service; set this to hide
	// the "Run" controls entirely.
	DisableRunner bool
	// DisableSitemap and DisableRobots suppress generation of sitemap.xml and
	// robots.txt respectively. Both are generated by default.
	DisableSitemap bool
	DisableRobots  bool
}

// ConfigLink is a labelled hyperlink used for the top navigation and footer
// social links. Icon is an optional lucide icon name (rendered for social links).
type ConfigLink struct {
	Label string `yaml:"label"`
	URL   string `yaml:"url"`
	Icon  string `yaml:"icon"`
}

// AnalyticsConfig configures an optional analytics snippet. Provider is one of
// "ga4", "gtm", or "plausible"; ID is the measurement/container/domain id.
type AnalyticsConfig struct {
	Provider string `yaml:"provider"`
	ID       string `yaml:"id"`
}

type RenderMode string

const (
	LiveRender RenderMode = "live_render"
	PreRender  RenderMode = "pre_render"
)

func WithSiteAddress(addr string) SiteOption {
	return func(s *Site) {
		s.addr = strings.TrimSpace(addr)
	}
}

func WithSiteTitle(title string) SiteOption {
	return func(s *Site) {
		s.App.Title = strings.TrimSpace(title)
	}
}

// WithSiteLogo sets a single brand logo used in both light and dark themes.
// Use WithSiteLogoLight / WithSiteLogoDark to vary the logo per theme.
func WithSiteLogo(logoURL string) SiteOption {
	return func(s *Site) {
		url := strings.TrimSpace(logoURL)
		s.App.LogoLight = url
		s.App.LogoDark = url
	}
}

func WithSiteLogoLight(logoURL string) SiteOption {
	return func(s *Site) {
		s.App.LogoLight = strings.TrimSpace(logoURL)
	}
}

func WithSiteLogoDark(logoURL string) SiteOption {
	return func(s *Site) {
		s.App.LogoDark = strings.TrimSpace(logoURL)
	}
}

func WithSiteLang(lang string) SiteOption {
	return func(s *Site) {
		s.App.Lang = strings.TrimSpace(lang)
	}
}

func WithSiteThemeColor(color string) SiteOption {
	return func(s *Site) {
		s.App.ThemeColor = strings.TrimSpace(color)
	}
}

func WithSiteDescription(description string) SiteOption {
	return func(s *Site) {
		s.App.Description = strings.TrimSpace(description)
	}
}

func WithSiteFooter(footer string) SiteOption {
	return func(s *Site) {
		s.App.Footer = strings.TrimSpace(footer)
	}
}

func WithSiteOGImage(imagePath string) SiteOption {
	return func(s *Site) {
		s.App.OGImagePath = strings.TrimSpace(imagePath)
	}
}

func WithSiteTwitterImage(imagePath string) SiteOption {
	return func(s *Site) {
		s.App.TwitterImagePath = strings.TrimSpace(imagePath)
	}
}

func WithSiteTwitterSite(handle string) SiteOption {
	return func(s *Site) {
		s.App.TwitterSite = strings.TrimSpace(handle)
	}
}

func WithSiteTwitterCreator(handle string) SiteOption {
	return func(s *Site) {
		s.App.TwitterCreator = strings.TrimSpace(handle)
	}
}

func WithSiteImageAlt(alt string) SiteOption {
	return func(s *Site) {
		s.App.ImageAlt = strings.TrimSpace(alt)
	}
}

func WithSiteNavLinks(links ...ConfigLink) SiteOption {
	return func(s *Site) {
		s.App.NavLinks = links
	}
}

func WithSiteSocialLinks(links ...ConfigLink) SiteOption {
	return func(s *Site) {
		s.App.SocialLinks = links
	}
}

func WithSiteAnalytics(provider, id string) SiteOption {
	return func(s *Site) {
		s.App.Analytics = AnalyticsConfig{
			Provider: strings.ToLower(strings.TrimSpace(provider)),
			ID:       strings.TrimSpace(id),
		}
	}
}

// WithSiteSitemapEnabled toggles generation of sitemap.xml (enabled by default).
func WithSiteSitemapEnabled(enabled bool) SiteOption {
	return func(s *Site) {
		s.App.DisableSitemap = !enabled
	}
}

// WithSiteRobotsEnabled toggles generation of robots.txt (enabled by default).
func WithSiteRobotsEnabled(enabled bool) SiteOption {
	return func(s *Site) {
		s.App.DisableRobots = !enabled
	}
}

func WithSiteContentDir(dir string) SiteOption {
	return func(s *Site) {
		s.App.ContentDir = strings.TrimSpace(dir)
	}
}

func WithSiteSidebarDepth(depth int) SiteOption {
	return func(s *Site) {
		s.App.SidebarDepth = depth
	}
}

func WithSiteURL(siteURL string) SiteOption {
	return func(s *Site) {
		s.App.SiteURL = strings.TrimSpace(siteURL)
	}
}

func WithSiteMode(mode RenderMode) SiteOption {
	return func(s *Site) {
		s.App.Mode = mode
	}
}

// WithSiteExportDir makes Start() export a static build into dir (instead of
// serving) — convenient for CI. Equivalent to setting the EXPORT_DIR env var or
// calling Site.Export(dir) directly.
func WithSiteExportDir(dir string) SiteOption {
	return func(s *Site) {
		s.App.ExportDir = strings.TrimSpace(dir)
	}
}

// exportDir returns the configured static-export target, falling back to the
// EXPORT_DIR environment variable.
func (a *App) exportDir() string {
	if d := strings.TrimSpace(a.ExportDir); d != "" {
		return d
	}
	return strings.TrimSpace(os.Getenv("EXPORT_DIR"))
}

// WithSiteRunnerEnabled toggles the in-browser Go runner. It is enabled by
// default; pass false to hide the "Run" controls across the site.
func WithSiteRunnerEnabled(enabled bool) SiteOption {
	return func(s *Site) {
		s.App.DisableRunner = !enabled
	}
}

// GetRunnerEnabled reports whether the client-side runner should be active.
// It defaults to on (execution is client-side, so there is nothing to provision)
// and can be turned off via WithSiteRunnerEnabled(false) or PLAYGROUND_ENABLED.
func (a *App) GetRunnerEnabled() bool {
	switch strings.ToLower(strings.TrimSpace(os.Getenv("PLAYGROUND_ENABLED"))) {
	case "0", "false", "no", "off":
		return false
	case "1", "true", "yes", "on":
		return true
	}
	return !a.DisableRunner
}

func (a *App) mode() RenderMode {
	raw := strings.TrimSpace(string(a.Mode))
	if raw == "" {
		raw = strings.TrimSpace(os.Getenv("APP_MODE"))
	}
	if raw == "" {
		raw = strings.TrimSpace(os.Getenv("APP_ENV"))
	}
	if raw == "" {
		raw = strings.TrimSpace(os.Getenv("GO_ENV"))
	}
	if raw == "" {
		raw = strings.TrimSpace(os.Getenv("ENV"))
	}

	return ParseRenderMode(raw)
}

func ParseRenderMode(raw string) RenderMode {
	normalized := strings.ToLower(strings.TrimSpace(raw))

	switch normalized {
	case "prerender", "pre-render", "pre_render", "pre", "prod", "production":
		return PreRender
	case "liverender", "live-render", "live_render", "live", "dev", "development":
		return LiveRender
	default:
		return LiveRender
	}
}

func (a *App) contentDir() string {
	if strings.TrimSpace(a.ContentDir) == "" {
		return "content"
	}
	return filepath.Clean(a.ContentDir)
}

func (a *App) sidebarDepth() int {
	if a.SidebarDepth <= 0 {
		return 2
	}
	return a.SidebarDepth
}

func (a *App) siteURL() string {
	if strings.TrimSpace(a.SiteURL) != "" {
		return normalizeBaseURL(a.SiteURL)
	}
	if env := strings.TrimSpace(os.Getenv("SITE_URL")); env != "" {
		return normalizeBaseURL(env)
	}
	return defaultSiteURL
}

func (a *App) siteTitle() string {
	if strings.TrimSpace(a.Title) != "" {
		return strings.TrimSpace(a.Title)
	}
	return defaultSiteName
}

func (a *App) logoLight() string {
	return strings.TrimSpace(a.LogoLight)
}

func (a *App) logoDark() string {
	return strings.TrimSpace(a.LogoDark)
}

func (a *App) lang() string {
	if l := strings.TrimSpace(a.Lang); l != "" {
		return l
	}
	return "en"
}

func (a *App) imageAlt() string {
	if alt := strings.TrimSpace(a.ImageAlt); alt != "" {
		return alt
	}
	return a.siteTitle()
}

func (a *App) sitemapEnabled() bool { return !a.DisableSitemap }
func (a *App) robotsEnabled() bool  { return !a.DisableRobots }

func (a *App) ogImagePath() string {
	if strings.TrimSpace(a.OGImagePath) != "" {
		return strings.TrimSpace(a.OGImagePath)
	}
	return defaultOGImagePath
}

func (a *App) twitterImagePath() string {
	if strings.TrimSpace(a.TwitterImagePath) != "" {
		return strings.TrimSpace(a.TwitterImagePath)
	}
	return defaultTwitterImagePath
}
